### ISSUE TITLE
Filter by language/tech

### ISSUE THREAD

**Issue by JoeyEbach** [JoeyEbach/INDIVIDUAL-ASSESSMENT-vocab-YOU-lary#13]
When the user logs in to the site, below the navbar they will see 5 filtering buttons. When the user clicks on a filtering button, only those entry cards that match the filter will appear.

This will require: 

- [x] #filterButton div added to domBuilder.js
- [x] filterButtons.js function that renders boostrap buttons to #filterButton div
- [x] addEventListener to filter buttons 
- [x] use GET all entries and a .filter to display the filtered entries

**Comment by ajawashington** [comment]
Love how you outline this with all your technical requirements! 🚀
