### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by JoeyEbach** [JoeyEbach/INDIVIDUAL-ASSESSMENT-vocab-YOU-lary#3]
https://dbdiagram.io/d/64f36d4402bd1c4a5edaa299

**Comment by ajawashington** [comment]
@JoeyEbach Since you are not saving your user object into your database (it is being saved in OAuth instead) you do not need a user table on your ERD and no need to specify where the connection is.

Also, the FirebaseKey is the entry primary key so it will not be connected to the user table. ❇️
