### ISSUE TITLE
Create a vocabulary entry

### ISSUE THREAD

**Issue by JoeyEbach** [JoeyEbach/INDIVIDUAL-ASSESSMENT-vocab-YOU-lary#8]
When the user clicks the Create Entry button in the navbar, a modal form will appear with the following input fields: 

- [x] title
- [x] definition
- [x] Language/Tech

Non-input data to gather:

- [x] time submitted 
- [x] userId [pull from user object]

This will require:

- [x] #createEntry div in domBuilder
- [x] createEntry.js function that renders the boostrap form modal to the div 
- [x] addEventListener to navbar Create Entry button in domEvents.js function
- [x] POST fetch for Create Entry form 
- [x] addEventListener to submit button in formEvents.js function
- [x] the formEvent will include the creation of a newEntry object (payload)
- [x] payload will be pushed to Create Entry POST fetch

After the user has submitted the form, the form should reset, disappear, and the newly created card should appear on the dom along with the user's other vocabulary cards.

**Comment by ajawashington** [comment]
Beautifully written ticket! 🚀
